// <auto-generated />
using BTCPayServer.Plugins.Nano;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Nano.Data.Migrations
{
    [DbContext(typeof(MyPluginDbContext))]
    [Migration("20250918111302_InvoiceAdhocAddress")]
    partial class InvoiceAdhocAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Nano")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Nano.Data.InvoiceAdhocAddress", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("PrivateAddress")
                        .HasColumnType("text");

                    b.Property<string>("PublicAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InvoiceAdhocAddress", "BTCPayServer.Plugins.Nano");
                });
#pragma warning restore 612, 618
        }
    }
}
