// <auto-generated />
using BTCPayServer.Plugins.Nano;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Nano.Migrations
{
    [DbContext(typeof(MyPluginDbContext))]
    [Migration("20251106142320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Nano")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Nano.Data.InvoiceAdhocAddress", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("account")
                        .HasColumnType("text");

                    b.Property<string>("invoiceId")
                        .HasColumnType("text");

                    b.Property<string>("privateAddress")
                        .HasColumnType("text");

                    b.Property<string>("publicAddress")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("InvoiceAdhocAddress", "BTCPayServer.Plugins.Nano");
                });
#pragma warning restore 612, 618
        }
    }
}
